### ISSUE TITLE
tried to migrate, rolled back due to multiple problems

### ISSUE THREAD

**Issue by seefood** [Shadowghost/mailcow-mailman3-dockerized#10]
steps taken:
1. full backup
2. docker-compose stop && docker-compose rm
3. create a new git branch and set it to track Shadowghost/mailcow-mailman3-dockerized's master
4. add back 0755 modifiers to all the entrypoint scripts and backup-restore as they didn't work.
5. generated config, saw it completely ignored the old settings, merged the two files.
6. docker-compose up -d, the users were working, but the mailbox content was not there, even after a restore. I assume it's a different path issue, but since it's a live machine I didn't want to waste time on debugging.
7. killed, removed all containers, returned to regular branch and restarted. luckily everything was working again.

Can the migration be tested and fixed please? also, can all the .sh files be committed as mode 0755?

**Comment by Shadowghost** [comment]
Thanks for the heads-up on the 0755 modes. I committed once on Windows, seems like it killed the permissions... Will fix it next time.
It is intentional, that the current settings are ignored, since I didn't write something like the "update.sh" script in the main repo for migration. You need to manually copy your passphrases and possible other changes to the new .env file.
No idea why your users do not have their mailbox content. Did you upgrade to the lastest mailcow master before switching branches? There were some changes to mailboxes in the last weeks.

BTW: You can just clone this repo in an own directory, no need to possibly mess up your current repo. Since the docker-compose project names are the same they should use the same volumes.

**Comment by seefood** [comment]
I'm pretty sure I did upgrade before the switch. I thought maybe there was a different path to the Maildirs or something, but I didn't have time to investigate, I just rolled back, since it's a live system. What the pop users did lose though are the marks of their last pull, so the entire inbox came down again for those that don't like deleting after pulling. but it could also have been because I had to run a restore.

Also, the project names are not the same. mine was mailcow by default, yours is mailcowdockerized. I don't remember changing mine, but maybe I did to keep it short? donno, can't remember now.

But in the bottom line, from the 10 minutes I played around with it, I got the impression the integration is a far cry from what I hoped. The way I saw it (Unless I missed something?), the mailman gets one subdomain that's not shared with the rest, so I can't really have both mailboxes and mailing lists on the same domain and I can only have lists on one domain. Is that correct?

**Comment by Shadowghost** [comment]
Yeah that's right the "integration" from mailman to mailcow is not really existent. Mailman utilizes it's own subdomain, own volumes and requires an webserver as proxy for displaying because I didn't want to edit mailcow configurations. As I said this was not planned as a permanent solution, but it should work as it is right now (at least i does for me but I didn't migrate from an existing mailcow install).
