### ISSUE TITLE
Linode Guide

### ISSUE THREAD

**Issue by ylluminate** [Shadowghost/mailcow-mailman3-dockerized#2]
Mind writing up a guide for Linode? They'll pay up to $300 for a guide and your package would sure be handy: https://linode.com/docs/contribute/

**Comment by Shadowghost** [comment]
Thanks for the suggestion.
This setup was planned as a temporary workaround until mailcow upstreams mailman3 integration. I'm updating it regulary because mailman integration on mailcow's dev branch is on hold (the dev branch itself isn't even in sync with mailcow master). It's just a dirty workaround, there are some kinks to it (like no free choice of subnets because the used mailman images hardcode some IPs) and I am not planning on "fixing" those. 
Whoever is willing to use this setup can do so but (at least atm) I don't plan to do anything except merging mailcow changes.
